version: "3.9"

services:
  web:
    image: "test"
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "80:80"
    networks:
      - web_network
    command: ./entrypoint.sh
    stdin_open: true
    tty: true
    cap_drop:
    - ALL
    cap_add:
    - SETGID
    - SETUID
    - CHOWN
    - FOWNER
    - DAC_OVERRIDE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /var/run/docker.sock:/run/docker.sock

networks:
  web_network:
    driver: bridge
