version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "80:80"
    networks:
      - mynetwork
    stdin_open: true
    tty: true
    cap_drop:
    - ALL
    cap_add:
    - SETGID
    - SETUID
    - CHOWN
    - FOWNER
    - DAC_OVERRIDE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /var/run/docker.sock:/run/docker.sock
networks:
  mynetwork:
    driver: bridge